--- # roles/mysql-server/tasks/main.yml
# mysql-server

  - name: Set MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
    changed_when: false

  - name: Confirm MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
    changed_when: false

  - name: Install mysql-server
    apt: 
      package: '{{ item }}' 
      state: present 
      update_cache: yes 
      cache_valid_time: 3600
    when: ansible_os_family == 'Debian'
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb
    notify:
      restart mysql

  - name: Secures the MySQL root user
    mysql_user: 
      user: "{{ MySQL_root_username }}" 
      password: "{{ MySQL_root_pass }}" 
      host: "{{ item }}" 
      login_password: "{{ MySQL_root_pass}}" 
      login_user: "{{ MySQL_root_username }}"
      priv: '*.*:ALL,GRANT'
      state: present
    with_items:
      - '127.0.0.1'
      - 'localhost'
      - '%'
    notify:
      restart mysql

  - name: Removes anonymous user accounts
    mysql_user:
      user: ""
      login_password: "{{ MySQL_root_pass}}" 
      login_user: "{{ MySQL_root_username }}"
      host_all: yes
      state: absent
      
  - name: Allow database accept connection from webservers
    replace:
      dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      regexp: '^bind-address		= 127.0.0.1'
      replace: 'bind-address		= 0.0.0.0'
    notify:
      restart mysql

    # lineinfile:
  #   dest: /etc/automysqlbackup/automysqlbackup.conf
  #   regexp: '^{{ item.regexp }}'
  #   line: '{{ item.replace }}'
  # with_items:
  #   - { regexp: "#CONFIG_mysql_dump_username='root'", replace: "CONFIG_mysql_dump_username='MY_SQL_ROOT_USER'" }

