--- # Very good to know every detail about remote host deployed with this ansible playbook
  - name: Display all facts known of host
    debug:
      var: hostvars[inventory_hostname]
    when: show_facts
