# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|


    config.vm.provider "docker" do |d|
      # docker images 
      # docker pull ubuntu:18.04
      d.image = "ubuntu:18.04"
      d.name = "ubuntu-18"
      d.cmd = ["tail", "-f", "/dev/null"]
    end

    
end
