--- 
  - name: Nginx configuration for the App
    template:
      src: templates/nginx-config.j2
      dest: "/etc/nginx/sites-available/{{ nginx_webapp_url }}"
      force: yes
    register: nginx_conf

  - name: Symlinks file for nginx
    file:
      src: "/etc/nginx/sites-available/{{ nginx_webapp_url }}"
      dest: "/etc/nginx/sites-enabled/{{ nginx_webapp_url }}"
      state: link

  - name: Unlink default configuration and use the nginx configuration for the App
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Test Nginx configuration and exit
    become: yes
    command: nginx -t
    changed_when: false
    register: nginx_test

  - name: Reload Nginx configuration based on the 'Test Nginx configuration and exit' task
    become: yes
    command: service nginx reload
    # when: nginx_test.stdout == "test is successful"
    when: nginx_test is succeeded and nginx_conf.changed

